parameters:
  linux:
    network:
      interface:
        ens3:
          enabled: true
          name: ens3
          type: eth
          proto: static
          address: ${_param:single_address}
          netmask: ${_param:control_network_netmask}
          ipflush_onchange: true
          restart_on_ipflush: true
        ens4:
          enabled: true
          name: ens4
          type: eth
          proto: dhcp
        ens5:
          enabled: true
          name: ens5
          type: eth
          proto: static
          address: ${_param:tenant_address}
          netmask: ${_param:tenant_network_netmask}
          ipflush_onchange: true
          restart_on_ipflush: true
