# Virtual node default networking template
#
parameters:
  linux:
    network:
      interface:
        deploy_interface:
          name: ${_param:deploy_nic}
          enabled: true
          type: eth
          proto: dhcp
          mesh: deploy
        control_interface:
          name: ${_param:primary_first_nic}
          enabled: true
          type: eth
          proto: static
          address: ${_param:single_address}
          netmask: ${_param:control_network_netmask}
          post_up_cmds:
            - ip r rep 10.254.0.0/16 via ${_param:single_address}
          mesh: control
