classes:
- system.etcd.server.cluster
- system.haproxy.proxy.listen.kubernetes.apiserver
- system.keepalived.cluster.instance.kube_api_server_vip
- system.salt.minion.cert.etcd_server
- system.kubernetes.master.cluster
- system.kubernetes.master.auth.rbac
- system.kubernetes.control.roles.cluster-admin
- system.kubernetes.control.roles.fluentd-view
- cluster.cdodda-k8s-test.kubernetes.common
- cluster.cdodda-k8s-test.kubernetes.networking.virtual
- cluster.cdodda-k8s-test.infra
- cluster.cdodda-k8s-test.ceph.rook
parameters:
  _param:
    deploy_nic: ens4
    keepalived_k8s_apiserver_vip_address: ${_param:kubernetes_control_address}
    keepalived_k8s_apiserver_vip_interface: ens3
    keepalived_k8s_apiserver_vip_password: password
    keepalived_vip_virtual_router_id: 69
    primary_first_nic: ens3
    primary_second_nic: ens5
  etcd:
    server:
      setup:
        calico:
          key: /calico/ipam/v2/assignment/ipv4/block/${_param:calico_private_network}-${_param:calico_private_netmask}
          value: '{"masquerade":true,"cidr":"${_param:calico_private_network}/${_param:calico_private_netmask}"}'
      source:
        engine: docker_hybrid
      ssl:
        enabled: true
  kubernetes:
    common:
      addons:
        coredns:
          domain: ${_param:cluster_domain}
          server: ${_param:kubernetes_internal_dns_address}
        helm:
          enabled: false
        netchecker:
          enabled: true
    master:
      apiserver:
        insecure_address: 0.0.0.0
      etcd:
        ssl:
          enabled: true
      namespace:
        netchecker:
          enabled: true
      network:
        calico:
          etcd:
            ssl:
              enabled: true
          policy:
            enabled: false
        enabled: true
