classes:
- system.etcd.server.cluster
- system.haproxy.proxy.listen.kubernetes.apiserver
- system.keepalived.cluster.instance.kube_api_server_vip
- system.salt.minion.cert.etcd_server
- system.kubernetes.master.cluster
- system.kubernetes.master.auth.rbac
- system.kubernetes.control.roles.cluster-admin
- system.kubernetes.control.roles.fluentd-view
- cluster.cdodda-k8s-test.kubernetes.common
- cluster.cdodda-k8s-test.kubernetes.networking.virtual
- cluster.cdodda-k8s-test.infra
parameters:
  _param:
    deploy_nic: eth0
    primary_first_nic: eth1
    primary_second_nic: eth2
    keepalived_k8s_apiserver_vip_interface: ens3
    keepalived_k8s_apiserver_vip_address: ${_param:kubernetes_control_address}
    keepalived_k8s_apiserver_vip_password: password
  etcd:
    server:
      source:
        engine: docker_hybrid
      ssl:
        enabled: true
      setup:
        calico:
          # key: /calico/v1/ipam/v4/pool/${_param:calico_private_network}-${_param:calico_private_netmask}
          key: /calico/ipam/v2/assignment/ipv4/block/${_param:calico_private_network}-${_param:calico_private_netmask}
          value: '{"masquerade":true,"cidr":"${_param:calico_private_network}/${_param:calico_private_netmask}"}'
          # if IP-in-IP is required
          # value: '{"ipip":"tunl0","ipip_mode":"always","ipam":true,"disabled":false, "masquerade":true,"cidr":"${_param:calico_private_network}/${_param:calico_private_netmask}"}'
  kubernetes:
    master:
      etcd:
        ssl:
          enabled: true
      network:
        enabled: true
        calico:
          etcd:
            ssl:
              enabled: true
          policy:
            enabled: false
      namespace:
        netchecker:
          enabled: true

    common:
      addons:
        netchecker:
          enabled: true
        helm:
          enabled: false
        coredns:
          domain: ${_param:cluster_domain}
          server: ${_param:kubernetes_internal_dns_address}
