classes:
- system.linux.system.repo.mcp.salt
- system.linux.system.repo.mcp.apt_mirantis.glusterfs
- system.salt.minion.ca.salt_master
- system.salt.master.single
- system.salt.master.api
- system.reclass.storage.salt
- system.salt.master.pillar.composite.reclass
- system.reclass.storage.system.kubernetes_proxy_cluster
- system.salt.minion.cert.k8s_server
- system.reclass.storage.system.kubernetes_control_cluster
- service.jenkins.client
- system.jenkins.client.credential.salt
- system.jenkins.client.job.deploy.openstack
- cluster.cdodda-k8s-test.infra.salt_master_formulas
- cluster.cdodda-k8s-test.infra
- cluster.cdodda-k8s-test.infra.backup.client_common
- cluster.cdodda-k8s-test.infra.networking.config
- cluster.cdodda-k8s-test.infra.config.nodes
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: "https://github.com/Mirantis/mk-lab-salt-model.git"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    deploy_address: ${_param:infra_config_deploy_address}
    linux_system_codename: xenial
    salt_api_password_hash: "$6$sGnRlxGf$al5jMCetLP.vfI/fTl3Z0N7Za1aeiexL487jAtyRABVfT3NlwZxQGVhO7S1N8OwS/34VHYwZQA8lkXwKMN/GS1"
    salt_master_host: ${_param:infra_config_deploy_address}
    jenkins_git_url: 'git@cfg01:/home/repo'
    jenkins_gerrit_url: ${_param:jenkins_git_url}
    salt_api_password: hovno12345!
    jenkins_salt_api_url: "http://${_param:salt_master_host}:6969"
    jenkins_pipeline_library_url: git@cfg01:/home/repo/mcp-ci/pipeline-library
    http_proxy_address: ""
    http_proxy_port: ""
    http_proxy: ""
  jenkins:
    client:
      lib:
        pipeline-library:
          url: ${_param:jenkins_pipeline_library_url}
          branch: ${_param:jenkins_pipelines_branch}
      master:
        host: ${_param:salt_master_host}
        port: 8081
        password: r00tme
  salt:
    master:
      command_timeout: 600
      user:
        deploy:
          permissions: ${_param:salt_master_api_permissions}
      backup: true
    minion:
      backup: true

